// APIM v2 (StandardV2) with outbound VNet integration, fronting a private
// Foundry agent's Activity Protocol endpoint for Bot Framework Channel calls
// (Teams / M365 Copilot).
//
// PASTE-READY scaffold. Drop into ./infra/main.bicep alongside the resources
// generated by `azd ai agent init`, then re-run `azd up`. This file does NOT
// run `az` itself — that is the deploy boundary owned by azd.
//
// Parallel to byo-vnet-with-pe.bicep:
//   - byo-vnet-with-pe.bicep provisions the VNet + PE + Private DNS
//   - this file provisions APIM v2 + custom domain + VNet integration + the API
//
// What this provisions:
//   1. APIM v2 service (StandardV2) with system-assigned MI
//   2. Custom domain hostname (KV-backed cert; system MI must already have
//      `Key Vault Secrets User` on the KV — pre-grant before this Bicep runs)
//   3. VNet integration sub-resource pointing at a delegated subnet you pass in
//   4. One API (`activity-protocol`) with the inbound <validate-jwt> policy
//   5. One Product (`bot-channel-ingress`) with subscription-required = false
//
// What this DOES NOT do (intentionally):
//   - Provision the VNet, the delegated subnet, or NSGs (see byo-vnet-with-pe.bicep)
//   - Provision the Key Vault or upload the cert (BYO cert workflow)
//   - Provision the Foundry PE (see byo-vnet-with-pe.bicep)
//   - Provision the corporate edge DNAT / firewall (network team owns)
//   - Create the public DNS A record (use output `apimGatewayPublicIp`)
//   - Register `Microsoft.Web` RP (required for subnet delegation; subscription-Owner action)
//
// Subnet delegation requirement: the subnet you pass in MUST be delegated to
// `Microsoft.Web/serverFarms` and contain no other resources. Minimum /27.
// See MS Learn: https://learn.microsoft.com/azure/api-management/integrate-vnet-outbound
//
// Tracked: TD-23 (inbound-firewall coverage for Teams / M365 Copilot → private Foundry).

targetScope = 'resourceGroup'

@description('Resource group location. APIM v2 SKU must be available here — check v2-service-tiers-overview.')
param location string = resourceGroup().location

@description('APIM service name. Globally unique (becomes the *.azure-api.net subdomain).')
param apimName string

@description('Publisher email shown in developer portal + service notifications.')
param publisherEmail string

@description('Publisher / organization name shown in developer portal.')
param publisherName string

@description('APIM SKU. Only StandardV2 and PremiumV2 support outbound VNet integration. BasicV2 is NOT supported.')
@allowed([
  'StandardV2'
  'PremiumV2'
])
param sku string = 'StandardV2'

@description('SKU capacity (units). 1 is sufficient for typical bot ingress; scale up if you front multiple agents.')
@minValue(1)
@maxValue(12)
param capacity int = 1

@description('Custom domain for the bot endpoint (e.g. bot.contoso.com). MUST be publicly resolvable — v2 tiers do not allow private-only domains for the Gateway endpoint.')
param customDomain string

@description('Key Vault secret URI for the TLS cert (PFX format, content-type application/x-pkcs12). The APIM system MI must have Key Vault Secrets User on the KV.')
param keyVaultSecretUri string

@description('Foundry account name (e.g. myacct from myacct.services.ai.azure.com).')
param foundryAccountName string

@description('Foundry project name (path segment in the Activity Protocol URL).')
param projectName string

@description('Deployed agent name (path segment in the Activity Protocol URL).')
param agentName string

@description('Bot Framework App ID = agent.identity.clientId after publish. Source: agent-status.json publish.bot_app_id. This is the audience claim validate-jwt enforces.')
param botAppId string

@description('Resource ID of the delegated subnet for outbound VNet integration. Delegation MUST be Microsoft.Web/serverFarms. Subnet must be dedicated (no other APIM, no other resources).')
param integrationSubnetId string

@description('Resource tags to apply to the APIM service.')
param tags object = {}

// ─── APIM service (StandardV2 by default) ─────────────────────────────────────
//
// Public inbound (Bot Framework Channel Adapter reaches this from the public
// backbone, restricted by the upstream corporate DNAT / firewall to Teams CIDRs).
// Outbound to private Foundry PE rides the VNet integration sub-resource.

resource apim 'Microsoft.ApiManagement/service@2024-05-01' = {
  name: apimName
  location: location
  sku: {
    name: sku
    capacity: capacity
  }
  identity: {
    type: 'SystemAssigned'
  }
  tags: tags
  properties: {
    publisherEmail: publisherEmail
    publisherName: publisherName
    // v2 tiers default to public access; VNet integration is outbound-only.
    publicNetworkAccess: 'Enabled'
    // Disable client cert negotiation on the gateway — not needed for Bot ingress.
    hostnameConfigurations: [
      {
        type: 'Proxy'
        hostName: customDomain
        keyVaultId: keyVaultSecretUri
        identityClientId: null    // null = use system-assigned MI
        defaultSslBinding: true
        negotiateClientCertificate: false
      }
    ]
  }
}

// ─── Outbound VNet integration (StandardV2 / PremiumV2 only) ──────────────────
//
// Per MS Learn (integrate-vnet-outbound): inbound NSG rules are NOT enforced
// in integration mode. Outbound rules to Storage + AzureKeyVault service tags
// ARE required on the subnet NSG (APIM dependencies).
//
// API version note: this sub-resource shape stabilized in 2024-05-01-preview;
// pin to a release that supports `networkConfiguration` cleanly.

resource apimVnetIntegration 'Microsoft.ApiManagement/service/networkConfigurations@2024-05-01-preview' = {
  parent: apim
  name: 'default'
  properties: {
    subnetResourceId: integrationSubnetId
  }
}

// ─── Named values (parameterize the JWT policy) ──────────────────────────────

resource nvBotAppId 'Microsoft.ApiManagement/service/namedValues@2024-05-01' = {
  parent: apim
  name: 'bot-app-id'
  properties: {
    displayName: 'bot-app-id'
    value: botAppId
    secret: false  // it's a public client ID, not a secret
  }
}

resource nvFoundryFqdn 'Microsoft.ApiManagement/service/namedValues@2024-05-01' = {
  parent: apim
  name: 'foundry-account-fqdn'
  properties: {
    displayName: 'foundry-account-fqdn'
    value: '${foundryAccountName}.services.ai.azure.com'
    secret: false
  }
}

resource nvProjectName 'Microsoft.ApiManagement/service/namedValues@2024-05-01' = {
  parent: apim
  name: 'project-name'
  properties: {
    displayName: 'project-name'
    value: projectName
    secret: false
  }
}

resource nvAgentName 'Microsoft.ApiManagement/service/namedValues@2024-05-01' = {
  parent: apim
  name: 'agent-name'
  properties: {
    displayName: 'agent-name'
    value: agentName
    secret: false
  }
}

// ─── API: activity-protocol ──────────────────────────────────────────────────

resource api 'Microsoft.ApiManagement/service/apis@2024-05-01' = {
  parent: apim
  name: 'activity-protocol'
  properties: {
    displayName: 'Bot Framework Activity Protocol (Foundry agent ingress)'
    path: 'messages'                      // public URL: https://<custom-domain>/messages
    protocols: ['https']
    serviceUrl: 'https://${foundryAccountName}.services.ai.azure.com/api/projects/${projectName}/agents/${agentName}/endpoint/protocols/activityprotocol'
    subscriptionRequired: false           // Bot Framework does not send subscription keys
  }
}

// Single POST operation matching the Bot Framework Channel Adapter contract.

resource opPost 'Microsoft.ApiManagement/service/apis/operations@2024-05-01' = {
  parent: api
  name: 'post-activity'
  properties: {
    displayName: 'POST activity'
    method: 'POST'
    urlTemplate: '/'
    request: {
      headers: [
        {
          name: 'Authorization'
          type: 'string'
          required: true
          description: 'Bot Framework JWT: Bearer <token>'
        }
      ]
    }
  }
}

// Inbound policy: validate-jwt against login.botframework.com + route to backend.
//
// IMPORTANT: this policy XML mirrors the canonical block in inbound-firewall.md.
// If you change it here, also update that doc — render-apim-policy.sh keeps them
// in lockstep for non-Bicep deploys.

resource apiPolicy 'Microsoft.ApiManagement/service/apis/policies@2024-05-01' = {
  parent: api
  name: 'policy'
  properties: {
    format: 'rawxml'
    value: '''
<policies>
  <inbound>
    <base />
    <validate-jwt header-name="Authorization"
                  failed-validation-httpcode="401"
                  failed-validation-error-message="Unauthorized. Bot Framework JWT required."
                  require-scheme="Bearer"
                  require-expiration-time="true"
                  require-signed-tokens="true"
                  clock-skew="300">
      <openid-config url="https://login.botframework.com/v1/.well-known/openidconfiguration"
                     validate-connectivity="false" />
      <audiences>
        <audience>{{bot-app-id}}</audience>
      </audiences>
      <issuers>
        <issuer>https://api.botframework.com</issuer>
      </issuers>
    </validate-jwt>
    <set-backend-service base-url="https://{{foundry-account-fqdn}}/api/projects/{{project-name}}/agents/{{agent-name}}/endpoint/protocols/activityprotocol" />
    <set-header name="Host" exists-action="override">
      <value>{{foundry-account-fqdn}}</value>
    </set-header>
  </inbound>
  <backend>
    <forward-request timeout="120" />
  </backend>
  <outbound>
    <base />
  </outbound>
  <on-error>
    <base />
  </on-error>
</policies>
'''
  }
  dependsOn: [
    nvBotAppId
    nvFoundryFqdn
    nvProjectName
    nvAgentName
  ]
}

// ─── Product: bot-channel-ingress (no subscription required) ─────────────────
//
// Wrapping the API in a Product is cheap and gives a stable handle for adding
// rate limits / logging / additional bots later.

resource product 'Microsoft.ApiManagement/service/products@2024-05-01' = {
  parent: apim
  name: 'bot-channel-ingress'
  properties: {
    displayName: 'Bot Channel Ingress'
    description: 'Front-door for Bot Framework Channel Adapter → private Foundry agents'
    subscriptionRequired: false
    approvalRequired: false
    state: 'published'
  }
}

resource productApi 'Microsoft.ApiManagement/service/products/apis@2024-05-01' = {
  parent: product
  name: api.name
}

// ─── Outputs ─────────────────────────────────────────────────────────────────

@description('Public IP(s) of the APIM gateway — use for the DNS A record on the custom domain.')
output apimGatewayPublicIp array = apim.properties.publicIPAddresses

@description('APIM default gateway hostname (the *.azure-api.net one).')
output apimGatewayHostname string = apim.properties.gatewayUrl

@description('ARM resource ID of the APIM service.')
output apimResourceId string = apim.id

@description('The fully-rendered backend URL the inbound policy will forward to.')
output apiBackendUrl string = 'https://${foundryAccountName}.services.ai.azure.com/api/projects/${projectName}/agents/${agentName}/endpoint/protocols/activityprotocol'

@description('The bot_app_id baked into the validate-jwt audience claim (echo so you can confirm against agent-status.json).')
output validatedBotAppId string = botAppId

@description('Public URL the Bot Service messaging endpoint should be set to.')
output messagingEndpointUrl string = 'https://${customDomain}/messages'
